# Generated by Django 3.2.4 on 2021-07-02 06:13

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20210702_0612"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=birthday.fields.BirthdayField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="birthday_dayofyear_internal",
            field=models.PositiveSmallIntegerField(
                default=None, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(
                default="Viorelovich", max_length=150, verbose_name="patronymic"
            ),
            preserve_default=False,
        ),
    ]
