# Generated by Django 3.2.4 on 2021-07-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("Активный", "Активный"),
                    ("INACTIVE", "Неактивный"),
                    ("DEACTIVATED", "Деактивированный"),
                ],
                max_length=11,
            ),
        ),
    ]
