# Generated by Django 3.2.4 on 2021-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20210706_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
