# Generated by Django 3.2.4 on 2021-06-26 01:35

from django.db import migrations, models
import src.admin_panel.services.media_services


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitehomepage",
            name="slider1",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.admin_panel.services.media_services.UploadToPathAndRename(
                    "images/site/home_page/slider"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="sitehomepage",
            name="slider2",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.admin_panel.services.media_services.UploadToPathAndRename(
                    "images/site/home_page/slider"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="sitehomepage",
            name="slider3",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.admin_panel.services.media_services.UploadToPathAndRename(
                    "images/site/home_page/slider"
                ),
            ),
        ),
    ]
