# Generated by Django 3.2.4 on 2021-06-26 02:11

from django.db import migrations, models
import src.admin_panel.services.media_services


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_auto_20210626_0135"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description",
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.admin_panel.services.media_services.UploadToPathAndRename(
                    "images/site/home_page/articles"
                ),
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
