# Generated by Django 3.2.4 on 2021-06-27 11:57

from django.db import migrations, models
import django.db.models.deletion
import src.admin_panel.services.media_services


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_auto_20210626_0211"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        upload_to=src.admin_panel.services.media_services.UploadToPathAndRename(
                            "docs"
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=src.admin_panel.services.media_services.UploadToPathAndRename(
                            "images/gallery-images"
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteAboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=3000)),
                ("title2", models.CharField(max_length=100)),
                ("description2", models.CharField(max_length=3000)),
                ("docs", models.ManyToManyField(to="admin_panel.Document")),
                (
                    "gallery",
                    models.ManyToManyField(
                        related_name="gallery", to="admin_panel.GalleryImage"
                    ),
                ),
                (
                    "gallery2",
                    models.ManyToManyField(
                        related_name="gallery2", to="admin_panel.GalleryImage"
                    ),
                ),
                (
                    "seo_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.seodata",
                    ),
                ),
            ],
        ),
    ]
