# Generated by Django 3.2.4 on 2021-06-29 04:29

from django.db import migrations, models
import src.admin_panel.services.media_services


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20210627_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=src.admin_panel.services.media_services.UploadToPathAndRename('docs')),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
