# Generated by Django 3.2.4 on 2021-06-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0008_siteservicepage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteServicePage",
            new_name="SiteServicesPage",
        ),
    ]
