# Generated by Django 3.2.4 on 2021-07-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0011_sitecontacts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SiteContacts",
            new_name="SiteContactsPage",
        ),
    ]
