# Generated by Django 3.2.4 on 2021-07-03 04:55

from django.db import migrations, models
import src.admin_panel.services.media_services


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_auto_20210702_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=src.admin_panel.services.media_services.UploadToPathAndRename('images/houses')),
        ),
        migrations.AlterField(
            model_name='house',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=src.admin_panel.services.media_services.UploadToPathAndRename('images/houses')),
        ),
        migrations.AlterField(
            model_name='house',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=src.admin_panel.services.media_services.UploadToPathAndRename('images/houses')),
        ),
        migrations.AlterField(
            model_name='house',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=src.admin_panel.services.media_services.UploadToPathAndRename('images/houses')),
        ),
        migrations.AlterField(
            model_name='house',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=src.admin_panel.services.media_services.UploadToPathAndRename('images/houses')),
        ),
    ]
