# Generated by Django 3.2.4 on 2021-07-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_auto_20210703_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000)),
                ('changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.tariff'),
        ),
    ]
