# Generated by Django 3.2.4 on 2021-07-09 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_service_is_removable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='services',
        ),
    ]
