# Generated by Django 3.2.4 on 2021-07-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_remove_serviceprice_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='service_price',
            field=models.ManyToManyField(to='admin_panel.ServicePrice'),
        ),
    ]
