# Generated by Django 3.2.4 on 2021-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_callrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='to_debtors',
            field=models.BooleanField(default=False),
        ),
    ]
