# Generated by Django 3.2.4 on 2021-07-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_auto_20210712_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
