# Generated by Django 3.2.4 on 2021-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0035_auto_20210712_1032"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="to_all",
            field=models.BooleanField(default=False),
        ),
    ]
