# Generated by Django 3.2.4 on 2021-07-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_alter_flat_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='account_flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flat_account', to='admin_panel.flat'),
        ),
    ]
