# Generated by Django 3.2.4 on 2021-07-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0040_auto_20210714_0308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.CharField(
                choices=[("Active", "Активный"), ("Inactive", "Неактивный")],
                max_length=10,
            ),
        ),
    ]
