# Generated by Django 3.2.4 on 2021-07-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0049_auto_20210716_0627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_flats",
                to="admin_panel.section",
            ),
        ),
    ]
