# Generated by Django 3.2.4 on 2021-07-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0050_alter_flat_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='number',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
