# Generated by Django 3.2.4 on 2021-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0053_receipt_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="period",
        ),
        migrations.AddField(
            model_name="receipt",
            name="period_end",
            field=models.DateField(default="1995-09-09"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="receipt",
            name="period_start",
            field=models.DateField(default="1995-05-05"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receipt",
            name="created",
            field=models.DateField(),
        ),
    ]
