# Generated by Django 3.2.4 on 2021-07-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0057_house_house_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="housestaff",
            old_name="user",
            new_name="house_staff",
        ),
    ]
