# Generated by Django 3.2.4 on 2021-07-22 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0058_rename_user_housestaff_house_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callrequest",
            name="created_by",
        ),
        migrations.AddField(
            model_name="callrequest",
            name="flat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.flat",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="callrequest",
            name="flat_owner",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="call_request_created_by",
                to="users.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="callrequest",
            name="master",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_request_master",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="callrequest",
            name="request_date",
            field=models.DateField(default="1995-05-14"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="callrequest",
            name="request_time",
            field=models.TimeField(default="16:05"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="callrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Новое"),
                    ("IN_WORK", "В работе"),
                    ("DONE", "Выполнено"),
                ],
                max_length=100,
            ),
        ),
    ]
