# Generated by Django 3.2.4 on 2021-07-23 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0059_auto_20210722_0825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="house_staff",
            field=models.ManyToManyField(
                blank=True,
                through="admin_panel.HouseStaff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipt_account",
                to="admin_panel.account",
            ),
        ),
    ]
