# Generated by Django 3.2.4 on 2021-08-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0061_alter_transaction_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callrequest",
            name="flat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admin_panel.flat",
            ),
        ),
    ]
