# Generated by Django 3.2.4 on 2021-08-02 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_panel", "0063_callrequest_personal_call"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="callrequest",
            name="personal_call",
        ),
        migrations.AddField(
            model_name="message",
            name="personal_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
