# Generated by Django 3.2.4 on 2021-08-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0065_alter_flat_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_flat",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flat_account",
                to="admin_panel.flat",
            ),
        ),
    ]
